before_script: npm install -g harp
script: bash ./deploy.sh
language: node_js
node_js:
- 5.7.1
env:
  global:
  - GH_REF: github.com/wadoteam/website-files.git
  - secure: QuyJR7cD1JRxXX6uzaPi40n88FYlN6kAQM8Zxt+CPHIL8Y9BykvhC0qDeda29gmOlOslCSReFlaWDw1mt+TkGRqTkzVckQ1ObcuXd7OqL0sqfygmiyjd5FCPSuSgIKUohTlpEZAtJge1PvnmerP0g56PIQ1u2VdlqiTA2fXSBmiBSlbfhfLfnpnb25+XaJnS6vvztkRPRncsoFcCpEp+Q9ZotoWOmPl7XejeHryiK0MJoEGNN0kgVlVigGUGWlSwY6NlFEh7P6CmfmUUtsGB4a7DVnJMMBkstI4HKadyyWAJrY3TQVbYo5Y6SaWzzqo/zhpTNpCKGWWJBZmTbhFTZYdKe/WXxhTXEemnzDA0cPpeOXU9DHJV7RaR8+wfxhNf+CNIB26imb6nV8ON1DiZoKNy3HhqT9a8m3djA8B07bHiRjtf5J5L8Y+jwjDvcdmP3RgJ+y3kiRTs7vZ9cHYKmzgL5btGnDDtAgyiS336wLlx6aDts/HsfajOVqcGXNLFcmL8uAzPKMiR9Q2F20v97oFeslAaWXEzvMGcXMTAQiTxA8f+b8xk5rpXGv/g4YqdnE0NWd0gezCDNz5T+pGvCLBBuYuZbVUjNdaS7UD3iAlo8YtqqYJZjD+0TFLlp2Hp2E+2SKCN6fmjMa4MVlp47pvtdhZj9s6dIHJPs0N16OM=
branches:
  only:
  - master
