script: bash ./deploy.sh
language: node_js
node_js:
- 5.7.1
env:
  global:
  - GH_REF: github.com/wadoteam/website-files.git
  - GH_TOKEN: 29b646477dd60c425630cc004833cae5c4a561e3
branches:
  only:
  - master
