before_script: npm install -g harp
script: bash ./deploy.sh
language: node_js
node_js:
- 5.7.1
env:
  global:
  - GH_REF: github.com/wadoteam/website-files.git
  - GH_TOKEN: 1e84956574ec43700b79d7b3733e351a4579578d
branches:
  only:
  - master
