script: bash ./deploy.sh
language: node_js
node_js:
- 5.7.1
env:
  global:
  - GH_REF: github.com/wadoteam/website-files.git
  - secure: VZLh7npNX5155wXL4DThfMZJJQYTBNcglHnOpZ1nUBHZoXwoCQgO7SBVFzpfTvLlpjf0uAHD0g8SdN3lcPbXcAeOuFuK3FepmhtwNMl2t9r3HZ28dngv6z/KkrYlqb4QYy9e8GK8+YD9UIeg2GJ1dy0m13ZB4tEKPhfo1E8WQX+yYrBEoX3kxGn++6utOs38je792GhDi5Dyb6AXZyUrTH0gAFhwsWKJOTRx9YZtRtG/rGXt1teyf1z9Ry+X8ZhbSxTR1NXIa47bBD/87BTHdM3/XURpXeYF9buWkfNqT+tcGckXU75FRwgLqMq0ITr3F5IWPApy+NKj6X+7qOQbLJZa4ZgXfs6bIL70H7noUdu6qzrjfRL6qq2xQFeMvJOHSeoxVxfzgM1YgXw7jnx0rQaOkK2mDAqeQBQMB5wb14zdp3XuRCS5Z+B3rI07qosunfSw30gLPbHqaNv05wOc/9591/CPQC6cfr5+LF+WU4DRyJp4tnSaYG6F3iNcASbhOU4lrIHnBhiYkBF8IOZWjldVem3bpt+KMxtctfjItUnGQPwP0KiLgbghPsEi2PHf7wNjeoEet8DNCGC4qlDAPMhTwiO/sVGyhwCXKjfwMmwvSiQvwSXY9qbKEh1OIb1JnzRLaSloZXTkRKKssyMtR6f/+0k0KFd+GiWOL2TGs9w=
branches:
  only:
  - master
